language: node_js
node_js:
  - "8.15.1"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - yarn global add vuepress
  - yarn install
  - vuepress build docs
  
script:
  - bash ./travis_deploy.sh
